encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.show_article, name="article"),
    path("search/", views.search, name="search"),
    path("random/", views.random_page, name="random"),
    path("create/", views.create, name="create"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from markdown2 import markdown
from . import util
from django import forms

import random


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def show_article(request, title):
    article = util.get_entry(title)
    if article == None:
        article = no_article(title)

    return render(
        request,
        "encyclopedia/article.html",
        {"article": markdown(article), "title": title},
    )


def no_article(title):
    return f'Article "{title}" not found. Try again'


def search(request):
    query = request.GET["q"]
    article = util.get_entry(query)
    if not article == None:
        return HttpResponseRedirect(
            reverse("encyclopedia:article", kwargs={"title": query})
        )

    result_list = []
    entries_list = util.list_entries()
    for i in entries_list:
        if i.lower().find(query.lower()) >= 0:
            result_list.append(i)

    if len(result_list) == 0:
        result_list = False

    return render(
        request,
        "encyclopedia/search.html",
        {
            "results": result_list,
        },
    )


def random_page(request):
    entries_list = util.list_entries()
    rand_entry_index = random.randint(0, len(entries_list) - 1)
    return HttpResponseRedirect(
        reverse(
            "encyclopedia:article", kwargs={"title": entries_list[rand_entry_index]}
        )
    )


class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title", max_length=100)
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))


def create(request):

    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            
            return HttpResponseRedirect(reverse("encyclopedia:index"))

    return render(
        request,
        "encyclopedia/create.html",
        {
            "form": NewEntryForm,
        },
    )

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
    <article>
        {{ article|safe }}
    </article>

{% endblock body %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new
{% endblock %}

{% block body %}
    <h1>Create new encyclopedia entry</h1>

    <form action=" {% url "encyclopedia:create" %} " method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href=" {% url 'encyclopedia:article' title=entry %} "> {{entry}} </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action=" {% url 'encyclopedia:search' %} " method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href=" {% url "encyclopedia:create" %} ">Create New Page</a>
                </div>
                <div>
                    <a href= " {% url "encyclopedia:random" %} ">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - Search
{% endblock title %}

{% block body %}
    
    {% if results %}
        <h2>Here are your search results:</h2>
        <ul>
            {% for item in results %}
                <li>
                    <a href="{% url 'encyclopedia:article' title=item %}"> {{item}} </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Nothing found by your criteria...</h2>
    {% endif %}

{% endblock body %}